// Generation of resolve_from_defaults() from #[theme(inherit_from = "...")] attributes.

use proc_macro2::TokenStream;
use quote::{format_ident, quote};
use syn::Ident;

use crate::parse::{FieldMeta, LayerMeta};

/// Generate `resolve_from_defaults()` impl block on the Option struct.
///
/// For each field with `#[theme(inherit_from = "defaults.X")]`, emits:
///   if self.field.is_none() { self.field = defaults.X; }
///
/// Two-level paths like "defaults.border.color" generate `defaults.border.color`.
pub(crate) fn gen_inherit(opt_name: &Ident, fields: &[FieldMeta], _layer: &LayerMeta) -> TokenStream {
    let stmts = gen_inherit_stmts(fields);

    quote! {
        impl #opt_name {
            /// Fill `None` fields from defaults using the ~55 uniform inheritance rules.
            /// Generated by `#[derive(ThemeWidget)]` from `#[theme(inherit_from = "...")]` attributes.
            pub(crate) fn resolve_from_defaults(&mut self, defaults: &crate::model::ThemeDefaults) {
                #stmts
            }
        }
    }
}

/// Generate inheritance assignment statements.
fn gen_inherit_stmts(fields: &[FieldMeta]) -> TokenStream {
    let mut stmts = Vec::new();

    for f in fields {
        if let Some(ref source) = f.inherit_from {
            let ident = &f.ident;
            let accessor = parse_defaults_path(source);
            stmts.push(quote! {
                if self.#ident.is_none() {
                    self.#ident = #accessor;
                }
            });
        }
    }

    quote! { #(#stmts)* }
}

/// Convert a dot-separated path like "defaults.border.color" into a token
/// stream like `defaults.border.color`.
///
/// The leading "defaults." is stripped because the method parameter is already
/// named `defaults`.
fn parse_defaults_path(path: &str) -> TokenStream {
    let stripped = path
        .strip_prefix("defaults.")
        .unwrap_or(path);

    let segments: Vec<Ident> = stripped
        .split('.')
        .map(|s| format_ident!("{}", s))
        .collect();

    quote! { defaults.#(#segments).* }
}
