// Generation of check_ranges() on the Resolved struct.

use proc_macro2::TokenStream;
use quote::{format_ident, quote};
use syn::Ident;

use crate::parse::{FieldCategory, FieldMeta, LayerMeta, RangeCheck};

/// Generate `check_ranges()` impl block on the Resolved struct.
pub(crate) fn gen_ranges(
    opt_name: &Ident,
    fields: &[FieldMeta],
    layer: &LayerMeta,
) -> TokenStream {
    let resolved_name = layer
        .resolved_name
        .clone()
        .unwrap_or_else(|| format_ident!("Resolved{}", opt_name));

    let check_stmts = gen_check_stmts(fields);

    quote! {
        impl #resolved_name {
            /// Validate field ranges for this widget theme.
            /// Generated by `#[derive(ThemeWidget)]` from `#[theme(check/range)]` attributes.
            pub(crate) fn check_ranges(
                &self,
                prefix: &str,
                errors: &mut Vec<crate::error::RangeViolation>,
            ) {
                #check_stmts
            }
        }
    }
}

/// Generate range check statements from field metadata.
fn gen_check_stmts(fields: &[FieldMeta]) -> TokenStream {
    let mut stmts = Vec::new();

    for f in fields {
        let ident = &f.ident;
        let field_name = ident.to_string();

        // Emit explicit range check if present
        if let Some(ref check) = f.range_check {
            match check {
                RangeCheck::NonNegative => {
                    stmts.push(quote! {
                        crate::resolve::validate_helpers::check_non_negative(
                            self.#ident,
                            &format!("{prefix}.{}", #field_name),
                            errors,
                        );
                    });
                }
                RangeCheck::Positive => {
                    stmts.push(quote! {
                        crate::resolve::validate_helpers::check_positive(
                            self.#ident,
                            &format!("{prefix}.{}", #field_name),
                            errors,
                        );
                    });
                }
                RangeCheck::Range { min, max } => {
                    let min_lit = *min as f32;
                    let max_lit = *max as f32;
                    stmts.push(quote! {
                        crate::resolve::validate_helpers::check_range_f32(
                            self.#ident,
                            #min_lit,
                            #max_lit,
                            &format!("{prefix}.{}", #field_name),
                            errors,
                        );
                    });
                }
                RangeCheck::RangeU16 { min, max } => {
                    let min_lit = *min;
                    let max_lit = *max;
                    stmts.push(quote! {
                        crate::resolve::validate_helpers::check_range_u16(
                            self.#ident,
                            #min_lit,
                            #max_lit,
                            &format!("{prefix}.{}", #field_name),
                            errors,
                        );
                    });
                }
            }
        }

        // Emit min_max_pair check if present
        if let Some(ref pair_ident) = f.min_max_pair {
            let pair_name = pair_ident.to_string();
            stmts.push(quote! {
                crate::resolve::validate_helpers::check_min_max(
                    self.#ident,
                    self.#pair_ident,
                    &format!("{prefix}.{}", #field_name),
                    &format!("{prefix}.{}", #pair_name),
                    errors,
                );
            });
        }

        // Auto-emit font range checks for nested ResolvedFontSpec fields
        if let FieldCategory::Nested { resolved_ty } = &f.category {
            if is_resolved_font_spec(resolved_ty) {
                stmts.push(quote! {
                    crate::resolve::validate_helpers::check_positive(
                        self.#ident.size,
                        &format!("{prefix}.{}.size", #field_name),
                        errors,
                    );
                    crate::resolve::validate_helpers::check_range_u16(
                        self.#ident.weight,
                        100,
                        900,
                        &format!("{prefix}.{}.weight", #field_name),
                        errors,
                    );
                });
            }
        }
    }

    quote! { #(#stmts)* }
}

/// Check if a type path refers to ResolvedFontSpec.
fn is_resolved_font_spec(ty: &syn::Type) -> bool {
    if let syn::Type::Path(type_path) = ty {
        if let Some(seg) = type_path.path.segments.last() {
            return seg.ident == "ResolvedFontSpec";
        }
    }
    false
}
