// Generation of validate_widget() on the Resolved struct.

use proc_macro2::TokenStream;
use quote::{format_ident, quote};
use syn::Ident;

use crate::parse::{FieldCategory, FieldMeta, LayerMeta};

/// Generate `validate_widget()` impl block on the Resolved struct.
pub(crate) fn gen_validate(
    opt_name: &Ident,
    fields: &[FieldMeta],
    layer: &LayerMeta,
) -> TokenStream {
    let resolved_name = layer
        .resolved_name
        .clone()
        .unwrap_or_else(|| format_ident!("Resolved{}", opt_name));

    let field_inits = gen_field_inits(fields);

    quote! {
        #[allow(dead_code)]
        #[allow(clippy::ptr_arg)] // Generated code passes Vec to helper functions that push
        impl #resolved_name {
            /// Extract and validate fields from the Option-based source struct.
            /// Generated by `#[derive(ThemeWidget)]` -- field paths use `stringify!()`.
            pub(crate) fn validate_widget(
                source: &#opt_name,
                prefix: &str,
                _dpi: f32,
                missing: &mut Vec<String>,
            ) -> Self {
                Self {
                    #field_inits
                }
            }
        }
    }
}

/// Generate field initialization expressions for validate_widget().
fn gen_field_inits(fields: &[FieldMeta]) -> TokenStream {
    let inits: Vec<TokenStream> = fields
        .iter()
        .map(|f| {
            let ident = &f.ident;
            let field_name = ident.to_string();

            match &f.category {
                FieldCategory::Option => {
                    quote! {
                        #ident: crate::resolve::validate_helpers::require(
                            &source.#ident,
                            &format!("{}.{}", prefix, #field_name),
                            missing,
                        ),
                    }
                }
                FieldCategory::SoftOption => {
                    quote! {
                        #ident: source.#ident,
                    }
                }
                FieldCategory::Nested { .. } => {
                    // Extract the Option<T> inner type for the ValidateNested call
                    let opt_ty = extract_option_inner_ty(&f.ty);
                    quote! {
                        #ident: <#opt_ty as crate::resolve::validate_helpers::ValidateNested>::validate_nested(
                            &source.#ident,
                            &format!("{}.{}", prefix, #field_name),
                            _dpi,
                            missing,
                        ),
                    }
                }
                FieldCategory::BorderPartial { .. } => {
                    quote! {
                        #ident: crate::resolve::validate_helpers::require_border_partial(
                            &source.#ident,
                            &format!("{}.{}", prefix, #field_name),
                            missing,
                        ),
                    }
                }
                FieldCategory::BorderOptional { .. } => {
                    quote! {
                        #ident: crate::resolve::validate_helpers::border_all_optional(
                            &source.#ident,
                        ),
                    }
                }
            }
        })
        .collect();

    quote! { #(#inits)* }
}

/// Extract T from Option<T>. Returns the type as-is if not Option.
fn extract_option_inner_ty(ty: &syn::Type) -> syn::Type {
    if let syn::Type::Path(type_path) = ty
        && let Some(seg) = type_path.path.segments.last()
        && seg.ident == "Option"
        && let syn::PathArguments::AngleBracketed(args) = &seg.arguments
        && let Some(syn::GenericArgument::Type(inner)) = args.args.first()
    {
        return inner.clone();
    }
    ty.clone()
}
