use std::collections::BTreeMap;
use std::fmt::Write;

use heck::ToUpperCamelCase;

use crate::schema::{MasterConfig, ThemeMapping};

/// Maps a known theme name string to its fully-qualified `native_theme::IconSet::` variant path.
///
/// Panics on unknown theme names (validation should catch these before codegen).
pub(crate) fn theme_name_to_icon_set(name: &str) -> &'static str {
    match name {
        "sf-symbols" => "native_theme::IconSet::SfSymbols",
        "segoe-fluent" => "native_theme::IconSet::SegoeIcons",
        "freedesktop" => "native_theme::IconSet::Freedesktop",
        "material" => "native_theme::IconSet::Material",
        "lucide" => "native_theme::IconSet::Lucide",
        _ => panic!("unknown theme name: {name}"),
    }
}

/// Generates a complete Rust source file implementing a custom icon enum with `IconProvider`.
///
/// The generated code includes:
/// - Header comment
/// - Enum definition with derives and `#[non_exhaustive]`
/// - `impl` block with `const ALL`
/// - `impl native_theme::IconProvider` with `icon_name()` and `icon_svg()` match arms
///
/// For DE-aware mapping values, only the `"default"` value is used in Phase 23.
/// Phase 24 will add desktop-environment dispatch codegen.
pub(crate) fn generate_code(
    config: &MasterConfig,
    mappings: &BTreeMap<String, ThemeMapping>,
    base_dir: &str,
) -> String {
    let enum_name = config.name.to_upper_camel_case();
    let mut out = String::new();

    // Header comment
    writeln!(out, "// Generated by native-theme-build -- do not edit").unwrap();
    writeln!(out).unwrap();

    // Enum definition
    writeln!(out, "#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]").unwrap();
    writeln!(out, "#[non_exhaustive]").unwrap();
    writeln!(out, "pub enum {enum_name} {{").unwrap();
    for role in &config.roles {
        let variant = role.to_upper_camel_case();
        writeln!(out, "    {variant},").unwrap();
    }
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // impl block with const ALL
    writeln!(out, "impl {enum_name} {{").unwrap();
    writeln!(out, "    pub const ALL: &[Self] = &[").unwrap();
    for role in &config.roles {
        let variant = role.to_upper_camel_case();
        writeln!(out, "        Self::{variant},").unwrap();
    }
    writeln!(out, "    ];").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // IconProvider impl
    writeln!(
        out,
        "impl native_theme::IconProvider for {enum_name} {{"
    )
    .unwrap();

    // icon_name()
    generate_icon_name(&mut out, config, mappings);

    writeln!(out).unwrap();

    // icon_svg()
    generate_icon_svg(&mut out, config, mappings, base_dir);

    writeln!(out, "}}").unwrap();

    out
}

/// Generates the `icon_name` method body with match arms for all role-theme combinations.
fn generate_icon_name(
    out: &mut String,
    config: &MasterConfig,
    mappings: &BTreeMap<String, ThemeMapping>,
) {
    writeln!(
        out,
        "    fn icon_name(&self, set: native_theme::IconSet) -> Option<&str> {{"
    )
    .unwrap();
    writeln!(out, "        match (self, set) {{").unwrap();

    // All themes (bundled + system) produce icon_name arms
    let all_themes = config
        .bundled_themes
        .iter()
        .chain(config.system_themes.iter());

    for theme_name in all_themes {
        let icon_set = theme_name_to_icon_set(theme_name);
        if let Some(mapping) = mappings.get(theme_name) {
            for role in &config.roles {
                if let Some(mv) = mapping.get(role) {
                    if let Some(icon_name) = mv.default_name() {
                        let variant = role.to_upper_camel_case();
                        writeln!(
                            out,
                            "            (Self::{variant}, {icon_set}) => Some(\"{icon_name}\"),"
                        )
                        .unwrap();
                    }
                }
            }
        }
    }

    writeln!(out, "            _ => None,").unwrap();
    writeln!(out, "        }}").unwrap();
    writeln!(out, "    }}").unwrap();
}

/// Generates the `icon_svg` method body with `include_bytes!` arms for bundled themes only.
fn generate_icon_svg(
    out: &mut String,
    config: &MasterConfig,
    mappings: &BTreeMap<String, ThemeMapping>,
    base_dir: &str,
) {
    writeln!(
        out,
        "    fn icon_svg(&self, set: native_theme::IconSet) -> Option<&'static [u8]> {{"
    )
    .unwrap();
    writeln!(out, "        match (self, set) {{").unwrap();

    // Only bundled themes produce icon_svg arms
    for theme_name in &config.bundled_themes {
        let icon_set = theme_name_to_icon_set(theme_name);
        if let Some(mapping) = mappings.get(theme_name) {
            for role in &config.roles {
                if let Some(mv) = mapping.get(role) {
                    if let Some(icon_name) = mv.default_name() {
                        let variant = role.to_upper_camel_case();
                        writeln!(
                            out,
                            "            (Self::{variant}, {icon_set}) => Some(include_bytes!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/{base_dir}/{theme_name}/{icon_name}.svg\"))),"
                        )
                        .unwrap();
                    }
                }
            }
        }
    }

    writeln!(out, "            _ => None,").unwrap();
    writeln!(out, "        }}").unwrap();
    writeln!(out, "    }}").unwrap();
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::BTreeMap;

    /// Build a test MasterConfig and mappings for a typical scenario:
    /// - enum name: "app-icon" (-> AppIcon)
    /// - roles: ["play-pause", "skip-forward"]
    /// - bundled themes: ["material"]
    /// - system themes: ["sf-symbols"]
    fn sample_config_and_mappings() -> (MasterConfig, BTreeMap<String, ThemeMapping>) {
        let config: MasterConfig = toml::from_str(
            r#"
name = "app-icon"
roles = ["play-pause", "skip-forward"]
bundled-themes = ["material"]
system-themes = ["sf-symbols"]
"#,
        )
        .unwrap();

        let material_mapping: ThemeMapping = toml::from_str(
            r#"
play-pause = "play_pause"
skip-forward = "skip_next"
"#,
        )
        .unwrap();

        let sf_mapping: ThemeMapping = toml::from_str(
            r#"
play-pause = "play.fill"
skip-forward = "forward.fill"
"#,
        )
        .unwrap();

        let mut mappings = BTreeMap::new();
        mappings.insert("material".to_string(), material_mapping);
        mappings.insert("sf-symbols".to_string(), sf_mapping);

        (config, mappings)
    }

    /// Build a config with a DE-aware mapping value.
    fn de_aware_config_and_mappings() -> (MasterConfig, BTreeMap<String, ThemeMapping>) {
        let config: MasterConfig = toml::from_str(
            r#"
name = "app-icon"
roles = ["play-pause"]
bundled-themes = ["material"]
system-themes = ["freedesktop"]
"#,
        )
        .unwrap();

        let material_mapping: ThemeMapping = toml::from_str(
            r#"
play-pause = "play_pause"
"#,
        )
        .unwrap();

        let freedesktop_mapping: ThemeMapping = toml::from_str(
            r#"
play-pause = { kde = "media-playback-start", default = "play" }
"#,
        )
        .unwrap();

        let mut mappings = BTreeMap::new();
        mappings.insert("material".to_string(), material_mapping);
        mappings.insert("freedesktop".to_string(), freedesktop_mapping);

        (config, mappings)
    }

    // === theme_name_to_icon_set tests ===

    #[test]
    fn theme_name_maps_sf_symbols() {
        assert_eq!(
            theme_name_to_icon_set("sf-symbols"),
            "native_theme::IconSet::SfSymbols"
        );
    }

    #[test]
    fn theme_name_maps_segoe_fluent() {
        assert_eq!(
            theme_name_to_icon_set("segoe-fluent"),
            "native_theme::IconSet::SegoeIcons"
        );
    }

    #[test]
    fn theme_name_maps_freedesktop() {
        assert_eq!(
            theme_name_to_icon_set("freedesktop"),
            "native_theme::IconSet::Freedesktop"
        );
    }

    #[test]
    fn theme_name_maps_material() {
        assert_eq!(
            theme_name_to_icon_set("material"),
            "native_theme::IconSet::Material"
        );
    }

    #[test]
    fn theme_name_maps_lucide() {
        assert_eq!(
            theme_name_to_icon_set("lucide"),
            "native_theme::IconSet::Lucide"
        );
    }

    #[test]
    #[should_panic]
    fn theme_name_panics_on_unknown() {
        theme_name_to_icon_set("nonexistent");
    }

    // === generate_code: header and enum tests ===

    #[test]
    fn generated_code_has_header_comment() {
        let (config, mappings) = sample_config_and_mappings();
        let output = generate_code(&config, &mappings, "icons");
        assert!(output.starts_with("// Generated by native-theme-build -- do not edit"));
    }

    #[test]
    fn generated_code_has_derives() {
        let (config, mappings) = sample_config_and_mappings();
        let output = generate_code(&config, &mappings, "icons");
        assert!(output.contains("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]"));
    }

    #[test]
    fn generated_code_has_non_exhaustive() {
        let (config, mappings) = sample_config_and_mappings();
        let output = generate_code(&config, &mappings, "icons");
        assert!(output.contains("#[non_exhaustive]"));
    }

    #[test]
    fn generated_code_has_enum_with_pascal_case_name() {
        let (config, mappings) = sample_config_and_mappings();
        let output = generate_code(&config, &mappings, "icons");
        assert!(output.contains("pub enum AppIcon {"));
    }

    #[test]
    fn generated_code_has_pascal_case_variants() {
        let (config, mappings) = sample_config_and_mappings();
        let output = generate_code(&config, &mappings, "icons");
        assert!(output.contains("PlayPause,"));
        assert!(output.contains("SkipForward,"));
    }

    #[test]
    fn generated_code_has_const_all() {
        let (config, mappings) = sample_config_and_mappings();
        let output = generate_code(&config, &mappings, "icons");
        assert!(output.contains("pub const ALL: &[Self]"));
        assert!(output.contains("Self::PlayPause,"));
        assert!(output.contains("Self::SkipForward,"));
    }

    // === generate_code: IconProvider impl tests ===

    #[test]
    fn generated_code_has_icon_provider_impl() {
        let (config, mappings) = sample_config_and_mappings();
        let output = generate_code(&config, &mappings, "icons");
        assert!(output.contains("impl native_theme::IconProvider for AppIcon"));
    }

    #[test]
    fn generated_code_has_icon_name_match_arms_for_bundled() {
        let (config, mappings) = sample_config_and_mappings();
        let output = generate_code(&config, &mappings, "icons");
        // material bundled theme should have icon_name arms
        assert!(
            output.contains(
                "(Self::PlayPause, native_theme::IconSet::Material) => Some(\"play_pause\")"
            ),
            "missing material play-pause icon_name arm. output:\n{output}"
        );
        assert!(
            output.contains(
                "(Self::SkipForward, native_theme::IconSet::Material) => Some(\"skip_next\")"
            ),
            "missing material skip-forward icon_name arm"
        );
    }

    #[test]
    fn generated_code_has_icon_name_match_arms_for_system() {
        let (config, mappings) = sample_config_and_mappings();
        let output = generate_code(&config, &mappings, "icons");
        // sf-symbols system theme should also have icon_name arms
        assert!(
            output.contains(
                "(Self::PlayPause, native_theme::IconSet::SfSymbols) => Some(\"play.fill\")"
            ),
            "missing sf-symbols play-pause icon_name arm. output:\n{output}"
        );
        assert!(
            output.contains(
                "(Self::SkipForward, native_theme::IconSet::SfSymbols) => Some(\"forward.fill\")"
            ),
            "missing sf-symbols skip-forward icon_name arm"
        );
    }

    #[test]
    fn generated_code_icon_name_has_wildcard() {
        let (config, mappings) = sample_config_and_mappings();
        let output = generate_code(&config, &mappings, "icons");
        // The icon_name match should end with _ => None
        assert!(
            output.contains("_ => None"),
            "missing wildcard arm in icon_name"
        );
    }

    // === generate_code: icon_svg tests ===

    #[test]
    fn generated_code_has_include_bytes_for_bundled() {
        let (config, mappings) = sample_config_and_mappings();
        let output = generate_code(&config, &mappings, "icons");
        assert!(
            output.contains(r#"include_bytes!(concat!(env!("CARGO_MANIFEST_DIR")"#),
            "missing include_bytes! with CARGO_MANIFEST_DIR"
        );
    }

    #[test]
    fn generated_code_include_bytes_uses_mapping_value_in_path() {
        let (config, mappings) = sample_config_and_mappings();
        let output = generate_code(&config, &mappings, "icons");
        // The SVG path should use the mapping value (play_pause), not the role name (play-pause)
        assert!(
            output.contains("/icons/material/play_pause.svg"),
            "SVG path should use mapping value 'play_pause', not role name. output:\n{output}"
        );
        assert!(
            output.contains("/icons/material/skip_next.svg"),
            "SVG path should use mapping value 'skip_next', not role name"
        );
    }

    #[test]
    fn generated_code_no_include_bytes_for_system_theme() {
        let (config, mappings) = sample_config_and_mappings();
        let output = generate_code(&config, &mappings, "icons");
        // System themes (sf-symbols) should NOT produce icon_svg match arms
        assert!(
            !output.contains("SfSymbols) => Some(include_bytes!"),
            "system themes should not produce include_bytes! arms"
        );
    }

    #[test]
    fn generated_code_icon_svg_has_wildcard() {
        let (config, mappings) = sample_config_and_mappings();
        let output = generate_code(&config, &mappings, "icons");
        // icon_svg function should have _ => None
        // We check this indirectly: the output must have at least two "_ => None" patterns
        // (one for icon_name, one for icon_svg)
        let count = output.matches("_ => None").count();
        assert!(
            count >= 2,
            "expected at least 2 wildcard arms (icon_name + icon_svg), found {count}"
        );
    }

    // === generate_code: DE-aware value tests ===

    #[test]
    fn generated_code_de_aware_uses_default_value() {
        let (config, mappings) = de_aware_config_and_mappings();
        let output = generate_code(&config, &mappings, "icons");
        // The DE-aware freedesktop mapping has { kde = "media-playback-start", default = "play" }
        // In Phase 23, codegen should use the default value "play"
        assert!(
            output.contains(
                "(Self::PlayPause, native_theme::IconSet::Freedesktop) => Some(\"play\")"
            ),
            "DE-aware icon_name should use default value 'play'. output:\n{output}"
        );
    }

    #[test]
    fn generated_code_de_aware_no_kde_specific_arm() {
        let (config, mappings) = de_aware_config_and_mappings();
        let output = generate_code(&config, &mappings, "icons");
        // In Phase 23, there should be no KDE-specific arm -- just the default
        assert!(
            !output.contains("media-playback-start"),
            "Phase 23 codegen should not generate KDE-specific arms"
        );
    }
}
