// Resolution inheritance phases: fills None fields from defaults and widget-to-widget chains.
//
// Hand-written inheritance rules (not expressible as simple field <- defaults.field attributes):
//
// 1. defaults_internal (9 rules): ordering-dependent chains between defaults fields
// 2. border sub-field inheritance (13 widgets): resolve_border() fills 4 sub-fields per border
// 3. font sub-field inheritance (19 widgets): resolve_font() fills 5 sub-fields per font
// 4. text_scale inheritance (4 entries): resolve_text_scale_entry() with computed line_height
// 5. safety nets (6 rules): per-platform fallbacks for input.caret_color, scrollbar.track_color, etc.
// 6. widget-to-widget chains (7 rules): depend on resolved font/border, must run after Phase 3
//
// The ~55 uniform "widget.field <- defaults.field" rules are generated by
// #[theme(inherit_from = "...")] attributes on widget struct fields.

use crate::model::border::{DefaultsBorderSpec, WidgetBorderSpec};
use crate::model::font::FontSize;
use crate::model::{DialogButtonOrder, FontSpec, TextScaleEntry, ThemeMode};

/// Resolve a per-widget font from defaults.
/// If the widget font is None, clone defaults entirely.
/// If the widget font is Some but has None sub-fields, fill from defaults.
fn resolve_font(widget_font: &mut Option<FontSpec>, defaults_font: &FontSpec) {
    match widget_font {
        None => {
            *widget_font = Some(defaults_font.clone());
        }
        Some(font) => {
            if font.family.is_none() {
                font.family = defaults_font.family.clone();
            }
            if font.size.is_none() {
                font.size = defaults_font.size;
            }
            if font.weight.is_none() {
                font.weight = defaults_font.weight;
            }
            if font.style.is_none() {
                font.style = defaults_font.style;
            }
            if font.color.is_none() {
                font.color = defaults_font.color;
            }
        }
    }
}

/// Resolve a per-widget border from defaults.border.
/// If the widget border is None, creates it from defaults.
/// If Some, fills None sub-fields from defaults.
/// `use_lg_radius`: if true, uses corner_radius_lg instead of corner_radius.
/// padding_horizontal and padding_vertical are NOT inherited (sizing fields).
fn resolve_border(
    widget_border: &mut Option<WidgetBorderSpec>,
    defaults_border: &DefaultsBorderSpec,
    use_lg_radius: bool,
) {
    let border = widget_border.get_or_insert_with(WidgetBorderSpec::default);
    if border.color.is_none() {
        border.color = defaults_border.color;
    }
    if border.corner_radius.is_none() {
        border.corner_radius = if use_lg_radius {
            defaults_border.corner_radius_lg
        } else {
            defaults_border.corner_radius
        };
    }
    if border.line_width.is_none() {
        border.line_width = defaults_border.line_width;
    }
    if border.shadow_enabled.is_none() {
        border.shadow_enabled = defaults_border.shadow_enabled;
    }
}

/// Resolve a text scale entry from defaults.
/// Creates the entry if None, fills sub-fields from defaults.font,
/// fills None sub-fields from defaults.font, then computes line_height
/// from defaults.line_height * resolved_size.
///
/// Per `inheritance-rules.toml [text_scale_inheritance]`:
/// - size inherits from defaults.font.size
/// - weight inherits from defaults.font.weight
fn resolve_text_scale_entry(
    entry: &mut Option<TextScaleEntry>,
    defaults_font: &FontSpec,
    defaults_line_height: Option<f32>,
) {
    let entry = entry.get_or_insert_with(TextScaleEntry::default);
    if entry.size.is_none() {
        entry.size = defaults_font.size;
    }
    if entry.weight.is_none() {
        entry.weight = defaults_font.weight;
    }
    if entry.line_height.is_none()
        && let (Some(lh_mult), Some(font_size)) = (defaults_line_height, entry.size)
    {
        entry.line_height = Some(match font_size {
            FontSize::Pt(_) => FontSize::Pt(lh_mult * font_size.raw()),
            FontSize::Px(_) => FontSize::Px(lh_mult * font_size.raw()),
        });
    }
}

/// Return the platform-appropriate dialog button order.
///
/// On Linux/KDE, the convention is leading-affirmative (OK on the left).
/// On Windows, GNOME, macOS, iOS the convention is trailing-affirmative.
pub(super) fn platform_button_order() -> DialogButtonOrder {
    #[cfg(target_os = "linux")]
    {
        if crate::detect::detect_linux_desktop() == crate::detect::LinuxDesktop::Kde {
            return DialogButtonOrder::PrimaryLeft;
        }
    }
    // Windows, GNOME, macOS, iOS all use primary-right
    DialogButtonOrder::PrimaryRight
}

impl ThemeMode {
    // --- Phase 1: Defaults internal chains ---

    pub(crate) fn resolve_defaults_internal(&mut self) {
        let d = &mut self.defaults;

        // selection_background <- accent_color
        if d.selection_background.is_none() {
            d.selection_background = d.accent_color;
        }
        // focus_ring_color <- accent_color
        if d.focus_ring_color.is_none() {
            d.focus_ring_color = d.accent_color;
        }
        // selection_inactive_background <- selection_background (MUST run after selection_background is set)
        if d.selection_inactive_background.is_none() {
            d.selection_inactive_background = d.selection_background;
        }
        // text_selection_background <- selection_background (inline text highlight defaults to selection)
        if d.text_selection_background.is_none() {
            d.text_selection_background = d.selection_background;
        }
        // text_selection_color <- selection_text_color
        if d.text_selection_color.is_none() {
            d.text_selection_color = d.selection_text_color;
        }
        // defaults.font.color <- defaults.text_color
        if d.font.color.is_none() {
            d.font.color = d.text_color;
        }
        // defaults.mono_font.color <- defaults.font.color (MUST run AFTER font.color is set)
        if d.mono_font.color.is_none() {
            d.mono_font.color = d.font.color;
        }
    }

    // --- Phase 2: Safety nets ---

    /// Phase 2: Safety nets -- fill widget fields that derive from defaults but
    /// are not part of the standard defaults-to-widget inheritance chain.
    ///
    /// These are deterministic derivations (no OS detection):
    /// - `input.caret_color` from `defaults.text_color`
    /// - `scrollbar.track_color` from `defaults.background_color`
    /// - `spinner.fill_color` from `defaults.accent_color`
    /// - `popover.background_color` from `defaults.background_color`
    /// - `list.background_color` from `defaults.background_color`
    /// - `dialog.background_color` from `defaults.background_color`
    pub(crate) fn resolve_safety_nets(&mut self) {
        // input.caret_color <- defaults.text_color
        if self.input.caret_color.is_none() {
            self.input.caret_color = self.defaults.text_color;
        }
        // scrollbar.track <- defaults.background_color
        if self.scrollbar.track_color.is_none() {
            self.scrollbar.track_color = self.defaults.background_color;
        }
        // spinner.fill <- defaults.accent_color (all platforms use accent)
        if self.spinner.fill_color.is_none() {
            self.spinner.fill_color = self.defaults.accent_color;
        }
        // popover.background <- defaults.background_color
        if self.popover.background_color.is_none() {
            self.popover.background_color = self.defaults.background_color;
        }
        // list.background <- defaults.background_color
        if self.list.background_color.is_none() {
            self.list.background_color = self.defaults.background_color;
        }
        // dialog.background <- defaults.background_color (per_platform fallback)
        if self.dialog.background_color.is_none() {
            self.dialog.background_color = self.defaults.background_color;
        }
    }

    // --- Phase 3: Widget-from-defaults ---

    pub(crate) fn resolve_widgets_from_defaults(&mut self) {
        self.resolve_color_inheritance();
        self.resolve_border_inheritance();
        self.resolve_font_inheritance();
        self.resolve_text_scale();
    }

    pub(crate) fn resolve_color_inheritance(&mut self) {
        // ~55 uniform "widget.field <- defaults.field" rules are generated by
        // #[theme(inherit_from)] attributes on widget struct fields.
        // Each widget's resolve_from_defaults() is called here at the start of
        // Phase 3, after Phase 1 (resolve_defaults_internal) has populated
        // derived defaults fields like text_selection_background.
        self.window.resolve_from_defaults(&self.defaults);
        self.button.resolve_from_defaults(&self.defaults);
        self.input.resolve_from_defaults(&self.defaults);
        self.checkbox.resolve_from_defaults(&self.defaults);
        self.menu.resolve_from_defaults(&self.defaults);
        self.tooltip.resolve_from_defaults(&self.defaults);
        self.scrollbar.resolve_from_defaults(&self.defaults);
        self.slider.resolve_from_defaults(&self.defaults);
        self.progress_bar.resolve_from_defaults(&self.defaults);
        self.tab.resolve_from_defaults(&self.defaults);
        self.sidebar.resolve_from_defaults(&self.defaults);
        self.toolbar.resolve_from_defaults(&self.defaults);
        self.status_bar.resolve_from_defaults(&self.defaults);
        self.list.resolve_from_defaults(&self.defaults);
        self.popover.resolve_from_defaults(&self.defaults);
        self.splitter.resolve_from_defaults(&self.defaults);
        self.separator.resolve_from_defaults(&self.defaults);
        self.switch.resolve_from_defaults(&self.defaults);
        self.dialog.resolve_from_defaults(&self.defaults);
        self.spinner.resolve_from_defaults(&self.defaults);
        self.combo_box.resolve_from_defaults(&self.defaults);
        self.segmented_control.resolve_from_defaults(&self.defaults);
        self.card.resolve_from_defaults(&self.defaults);
        self.expander.resolve_from_defaults(&self.defaults);
        self.link.resolve_from_defaults(&self.defaults);
    }

    pub(crate) fn resolve_border_inheritance(&mut self) {
        let defaults_border = &self.defaults.border;

        // 13 widgets with full border inheritance
        // corner_radius_lg widgets: window, popover, dialog
        resolve_border(&mut self.window.border, defaults_border, true);
        resolve_border(&mut self.button.border, defaults_border, false);
        resolve_border(&mut self.input.border, defaults_border, false);
        resolve_border(&mut self.checkbox.border, defaults_border, false);
        resolve_border(&mut self.tooltip.border, defaults_border, false);
        resolve_border(&mut self.progress_bar.border, defaults_border, false);
        resolve_border(&mut self.toolbar.border, defaults_border, false);
        resolve_border(&mut self.list.border, defaults_border, false);
        resolve_border(&mut self.popover.border, defaults_border, true);
        resolve_border(&mut self.dialog.border, defaults_border, true);
        resolve_border(&mut self.combo_box.border, defaults_border, false);
        resolve_border(&mut self.segmented_control.border, defaults_border, false);
        resolve_border(&mut self.expander.border, defaults_border, false);

        // Partial border: sidebar (color + line_width only)
        {
            let border = self
                .sidebar
                .border
                .get_or_insert_with(WidgetBorderSpec::default);
            if border.color.is_none() {
                border.color = defaults_border.color;
            }
            if border.line_width.is_none() {
                border.line_width = defaults_border.line_width;
            }
        }

        // Partial border: status_bar (color + line_width only)
        {
            let border = self
                .status_bar
                .border
                .get_or_insert_with(WidgetBorderSpec::default);
            if border.color.is_none() {
                border.color = defaults_border.color;
            }
            if border.line_width.is_none() {
                border.line_width = defaults_border.line_width;
            }
        }
    }

    pub(crate) fn resolve_font_inheritance(&mut self) {
        let defaults_font = &self.defaults.font;
        // 19 widget fonts
        resolve_font(&mut self.window.title_bar_font, defaults_font);
        resolve_font(&mut self.button.font, defaults_font);
        resolve_font(&mut self.input.font, defaults_font);
        resolve_font(&mut self.checkbox.font, defaults_font);
        resolve_font(&mut self.menu.font, defaults_font);
        resolve_font(&mut self.tooltip.font, defaults_font);
        resolve_font(&mut self.tab.font, defaults_font);
        resolve_font(&mut self.sidebar.font, defaults_font);
        resolve_font(&mut self.toolbar.font, defaults_font);
        resolve_font(&mut self.status_bar.font, defaults_font);
        resolve_font(&mut self.list.item_font, defaults_font);
        resolve_font(&mut self.list.header_font, defaults_font);
        resolve_font(&mut self.popover.font, defaults_font);
        resolve_font(&mut self.dialog.title_font, defaults_font);
        resolve_font(&mut self.dialog.body_font, defaults_font);
        resolve_font(&mut self.combo_box.font, defaults_font);
        resolve_font(&mut self.segmented_control.font, defaults_font);
        resolve_font(&mut self.expander.font, defaults_font);
        resolve_font(&mut self.link.font, defaults_font);

        // Exception: link.font.color inherits from defaults.link_color, NOT defaults.font.color
        // This MUST run AFTER the generic resolve_font call above
        if let Some(ref mut font) = self.link.font {
            font.color = self.defaults.link_color;
        }
    }

    pub(crate) fn resolve_text_scale(&mut self) {
        let defaults_font = &self.defaults.font;
        let defaults_lh = self.defaults.line_height;

        resolve_text_scale_entry(&mut self.text_scale.caption, defaults_font, defaults_lh);
        resolve_text_scale_entry(
            &mut self.text_scale.section_heading,
            defaults_font,
            defaults_lh,
        );
        resolve_text_scale_entry(
            &mut self.text_scale.dialog_title,
            defaults_font,
            defaults_lh,
        );
        resolve_text_scale_entry(&mut self.text_scale.display, defaults_font, defaults_lh);
    }

    // --- Phase 4: Widget-to-widget chains ---

    pub(crate) fn resolve_widget_to_widget(&mut self) {
        // inactive title bar <- active title bar
        if self.window.inactive_title_bar_background.is_none() {
            self.window.inactive_title_bar_background = self.window.title_bar_background;
        }
        if self.window.inactive_title_bar_text_color.is_none() {
            self.window.inactive_title_bar_text_color =
                self.window.title_bar_font.as_ref().and_then(|f| f.color);
        }
        // button.hover_text_color <- button.font.color (widget-to-widget)
        // Must run AFTER resolve_font_inheritance has populated button.font.color
        if self.button.hover_text_color.is_none() {
            self.button.hover_text_color = self.button.font.as_ref().and_then(|f| f.color);
        }
        // button.active_text_color <- button.font.color (widget-to-widget)
        if self.button.active_text_color.is_none() {
            self.button.active_text_color = self.button.font.as_ref().and_then(|f| f.color);
        }
        // tab.hover_text_color <- tab.font.color (widget-to-widget)
        if self.tab.hover_text_color.is_none() {
            self.tab.hover_text_color = self.tab.font.as_ref().and_then(|f| f.color);
        }
        // list.hover_text_color <- list.item_font.color (widget-to-widget)
        if self.list.hover_text_color.is_none() {
            self.list.hover_text_color = self.list.item_font.as_ref().and_then(|f| f.color);
        }
        // splitter.hover_color <- splitter.divider_color (widget-to-widget)
        if self.splitter.hover_color.is_none() {
            self.splitter.hover_color = self.splitter.divider_color;
        }
        // link.hover_text_color <- link.font.color (widget-to-widget)
        if self.link.hover_text_color.is_none() {
            self.link.hover_text_color = self.link.font.as_ref().and_then(|f| f.color);
        }
        // link.active_text_color <- link.font.color (widget-to-widget)
        if self.link.active_text_color.is_none() {
            self.link.active_text_color = self.link.font.as_ref().and_then(|f| f.color);
        }
    }
}

#[cfg(test)]
#[allow(clippy::expect_used)]
mod tests {
    /// Verify that every rule in inheritance-rules.toml [defaults_internal] section
    /// is covered by the hand-written implementation in this file.
    ///
    /// This test catches drift: if someone adds a rule to the TOML but forgets
    /// to implement it in Rust, this test fails.
    #[test]
    fn inheritance_rules_toml_covers_defaults_internal() {
        let toml_str = include_str!("../../../docs/inheritance-rules.toml");
        let table: toml::Table = toml_str.parse().expect("valid TOML");

        // [defaults_internal] section
        let defaults_internal = table
            .get("defaults_internal")
            .and_then(|v| v.as_table())
            .expect("[defaults_internal] section exists");

        // These are the fields that resolve_defaults_internal() handles.
        // If a new rule is added to the TOML, add the target field here too.
        let implemented_targets: &[&str] = &[
            "defaults.selection_background",
            "defaults.focus_ring_color",
            "defaults.selection_inactive_background",
            "defaults.text_selection_background",
            "defaults.text_selection_color",
            "defaults.font.color",
            "defaults.mono_font.color",
            "defaults.border.padding_horizontal",
            "defaults.border.padding_vertical",
        ];

        for key in defaults_internal.keys() {
            assert!(
                implemented_targets.contains(&key.as_str()),
                "inheritance-rules.toml [defaults_internal] has rule '{key}' \
                 but it is not listed in inheritance.rs implemented_targets. \
                 Either implement the rule or add it to the list."
            );
        }

        // Reverse check: every implemented target should be in the TOML
        for &target in implemented_targets {
            assert!(
                defaults_internal.contains_key(target),
                "inheritance.rs claims to implement '{target}' but it is not \
                 in inheritance-rules.toml [defaults_internal]"
            );
        }
    }

    /// Helper: parse inheritance-rules.toml once.
    fn load_rules_toml() -> toml::Table {
        let toml_str = include_str!("../../../docs/inheritance-rules.toml");
        toml_str.parse().expect("valid TOML")
    }

    /// Helper: extract a string array from a TOML value.
    fn toml_string_array(val: &toml::Value) -> Vec<String> {
        val.as_array()
            .expect("expected array")
            .iter()
            .map(|v| v.as_str().expect("expected string").to_string())
            .collect()
    }

    /// Helper: assert bidirectional coverage between a TOML key set and an explicit list.
    fn assert_bidirectional(section_name: &str, toml_keys: &[String], implemented: &[&str]) {
        for key in toml_keys {
            assert!(
                implemented.contains(&key.as_str()),
                "[{section_name}] TOML has '{key}' but it is not in the implemented list. \
                 Either implement the rule or add it to the test."
            );
        }
        for &target in implemented {
            assert!(
                toml_keys.iter().any(|k| k == target),
                "[{section_name}] implementation claims '{target}' but it is not in the TOML."
            );
        }
    }

    // --- [border_inheritance] bidirectional ---

    #[test]
    fn border_inheritance_widgets_match_toml() {
        let table = load_rules_toml();
        let section = table
            .get("border_inheritance")
            .and_then(|v| v.as_table())
            .expect("[border_inheritance] section exists");

        // Full border widgets (resolve_border with full inheritance)
        let toml_widgets = toml_string_array(
            section
                .get("widgets_with_border")
                .expect("widgets_with_border key"),
        );

        // These are the widgets that resolve_border_inheritance() calls resolve_border() on.
        let implemented_widgets: &[&str] = &[
            "window",
            "button",
            "input",
            "checkbox",
            "tooltip",
            "progress_bar",
            "toolbar",
            "list",
            "popover",
            "dialog",
            "combo_box",
            "segmented_control",
            "expander",
        ];
        assert_bidirectional(
            "border_inheritance.widgets_with_border",
            &toml_widgets,
            implemented_widgets,
        );
    }

    #[test]
    fn border_inheritance_lg_widgets_match_toml() {
        let table = load_rules_toml();
        let section = table
            .get("border_inheritance")
            .and_then(|v| v.as_table())
            .expect("[border_inheritance] section exists");

        let toml_lg = toml_string_array(
            section
                .get("corner_radius_lg_widgets")
                .expect("corner_radius_lg_widgets key"),
        );

        // These are the widgets where resolve_border() is called with use_lg_radius = true.
        let implemented_lg: &[&str] = &["window", "popover", "dialog"];
        assert_bidirectional(
            "border_inheritance.corner_radius_lg_widgets",
            &toml_lg,
            implemented_lg,
        );
    }

    // --- [font_inheritance] bidirectional ---

    #[test]
    fn font_inheritance_widgets_match_toml() {
        let table = load_rules_toml();
        let section = table
            .get("font_inheritance")
            .and_then(|v| v.as_table())
            .expect("[font_inheritance] section exists");

        let toml_fonts = toml_string_array(
            section
                .get("widgets_with_font")
                .expect("widgets_with_font key"),
        );

        // These are the widget font paths that resolve_font_inheritance() calls resolve_font() on.
        let implemented_fonts: &[&str] = &[
            "window.title_bar_font",
            "button.font",
            "input.font",
            "checkbox.font",
            "menu.font",
            "tooltip.font",
            "tab.font",
            "sidebar.font",
            "toolbar.font",
            "status_bar.font",
            "list.item_font",
            "list.header_font",
            "popover.font",
            "dialog.body_font",
            "dialog.title_font",
            "combo_box.font",
            "segmented_control.font",
            "expander.font",
            "link.font",
        ];
        assert_bidirectional(
            "font_inheritance.widgets_with_font",
            &toml_fonts,
            implemented_fonts,
        );
    }

    // --- [per_platform] bidirectional (safety nets) ---

    #[test]
    fn per_platform_rules_match_safety_nets() {
        let table = load_rules_toml();
        let section = table
            .get("per_platform")
            .and_then(|v| v.as_table())
            .expect("[per_platform] section exists");

        let toml_keys: Vec<String> = section.keys().cloned().collect();

        // These are the fields that resolve_safety_nets() fills.
        let implemented_safety_nets: &[&str] = &[
            "input.caret_color",
            "scrollbar.track_color",
            "spinner.fill_color",
            "popover.background_color",
            "list.background_color",
            "dialog.background_color",
        ];
        assert_bidirectional("per_platform", &toml_keys, implemented_safety_nets);
    }

    // --- [text_scale_inheritance] bidirectional ---

    #[test]
    fn text_scale_entries_match_toml() {
        let table = load_rules_toml();
        let section = table
            .get("text_scale_inheritance")
            .and_then(|v| v.as_table())
            .expect("[text_scale_inheritance] section exists");

        let toml_entries = toml_string_array(section.get("entries").expect("entries key"));

        // These are the entries that resolve_text_scale() processes.
        let implemented_entries: &[&str] =
            &["caption", "section_heading", "dialog_title", "display"];
        assert_bidirectional(
            "text_scale_inheritance.entries",
            &toml_entries,
            implemented_entries,
        );
    }

    // --- [uniform] bidirectional ---
    //
    // The [uniform] section contains rules implemented across multiple phases:
    //   - proc-macro-generated rules (via #[theme(inherit_from = "...")]) — Phase 3
    //   - widget-to-widget rules — Phase 4
    //   - partial border rules (sidebar/status_bar) — Phase 3
    //   - font color override (link.font.color) — Phase 3
    //   - safety-net-adjacent (scrollbar.thumb_*) — Phase 3

    #[test]
    fn uniform_rules_all_accounted_for() {
        let table = load_rules_toml();
        let section = table
            .get("uniform")
            .and_then(|v| v.as_table())
            .expect("[uniform] section exists");

        let toml_keys: Vec<String> = section.keys().cloned().collect();

        // Every [uniform] rule must appear in exactly one of these implementation categories.
        // Each rule is listed under its implementation method in inheritance.rs.

        // Category 1: proc-macro generated via #[theme(inherit_from = "defaults.*")]
        // These are implemented by resolve_from_defaults() on each widget struct.
        let proc_macro_rules: &[&str] = &[
            // window (§2.2)
            "window.background_color",
            "window.title_bar_background",
            // button (§2.3)
            "button.background_color",
            "button.primary_background",
            "button.primary_text_color",
            "button.disabled_opacity",
            "button.hover_background",
            "button.disabled_text_color",
            // input (§2.4)
            "input.background_color",
            "input.placeholder_color",
            "input.selection_background",
            "input.selection_text_color",
            "input.disabled_opacity",
            "input.disabled_text_color",
            // checkbox (§2.5)
            "checkbox.background_color",
            "checkbox.checked_background",
            "checkbox.indicator_color",
            "checkbox.disabled_opacity",
            "checkbox.disabled_text_color",
            // menu (§2.6)
            "menu.background_color",
            "menu.separator_color",
            "menu.icon_size",
            "menu.hover_background",
            "menu.hover_text_color",
            "menu.disabled_text_color",
            // tooltip (§2.7)
            "tooltip.background_color",
            // scrollbar (§2.8)
            "scrollbar.thumb_color",
            "scrollbar.thumb_hover_color",
            // slider (§2.9)
            "slider.fill_color",
            "slider.track_color",
            "slider.thumb_color",
            "slider.disabled_opacity",
            // progress_bar (§2.10)
            "progress_bar.fill_color",
            "progress_bar.track_color",
            // tab (§2.11)
            "tab.background_color",
            "tab.active_background",
            "tab.active_text_color",
            "tab.bar_background",
            // sidebar (§2.12)
            "sidebar.background_color",
            "sidebar.selection_background",
            "sidebar.selection_text_color",
            "sidebar.hover_background",
            // toolbar (§2.13)
            "toolbar.background_color",
            "toolbar.icon_size",
            // status_bar (§2.14)
            "status_bar.background_color",
            // list (§2.15)
            "list.selection_background",
            "list.selection_text_color",
            "list.header_background",
            "list.grid_color",
            "list.hover_background",
            "list.disabled_text_color",
            // switch (§2.21)
            "switch.checked_background",
            "switch.thumb_background",
            "switch.disabled_opacity",
            // combo_box (§2.24)
            "combo_box.background_color",
            "combo_box.disabled_opacity",
            "combo_box.disabled_text_color",
            // segmented_control (§2.25)
            "segmented_control.background_color",
            "segmented_control.active_background",
            "segmented_control.active_text_color",
            "segmented_control.disabled_opacity",
            // card (§2.26)
            "card.background_color",
            // splitter (§2.17)
            "splitter.divider_color",
            // separator (§2.18)
            "separator.line_color",
            "separator.line_width",
            // link (§2.28)
            "link.visited_text_color",
            "link.disabled_text_color",
        ];

        // Category 2: widget-to-widget chains (resolve_widget_to_widget, Phase 4)
        let widget_to_widget_rules: &[&str] = &[
            "window.inactive_title_bar_background",
            "window.inactive_title_bar_text_color",
            "button.hover_text_color",
            "button.active_text_color",
            "tab.hover_text_color",
            "list.hover_text_color",
            "splitter.hover_color",
            "link.hover_text_color",
            "link.active_text_color",
        ];

        // Category 3: partial border rules (resolve_border_inheritance, Phase 3)
        let partial_border_rules: &[&str] = &[
            "sidebar.border.color",
            "sidebar.border.line_width",
            "status_bar.border.color",
            "status_bar.border.line_width",
        ];

        // Category 4: font color override (resolve_font_inheritance, Phase 3)
        let font_override_rules: &[&str] = &["link.font.color"];

        // Category 5: widget-to-widget via list (resolve_widget_to_widget, Phase 4)
        let list_alternate_rule: &[&str] = &["list.alternate_row_background"];

        // Combine all categories
        let mut all_implemented: Vec<&str> = Vec::new();
        all_implemented.extend_from_slice(proc_macro_rules);
        all_implemented.extend_from_slice(widget_to_widget_rules);
        all_implemented.extend_from_slice(partial_border_rules);
        all_implemented.extend_from_slice(font_override_rules);
        all_implemented.extend_from_slice(list_alternate_rule);

        assert_bidirectional("uniform", &toml_keys, &all_implemented);
    }

    // --- [no_inheritance] negative check ---
    //
    // Fields in [no_inheritance] must NEVER appear as inheritance targets in any
    // of the implemented rule lists above.

    #[test]
    fn no_inheritance_fields_are_not_inherited() {
        let table = load_rules_toml();
        let section = table
            .get("no_inheritance")
            .and_then(|v| v.as_table())
            .expect("[no_inheritance] section exists");

        let no_inherit_fields = toml_string_array(section.get("fields").expect("fields key"));

        // Gather ALL implemented inheritance targets across all phases.
        // If any no_inheritance field appears here, we have a bug.
        let all_inherited_targets: &[&str] = &[
            // defaults_internal (Phase 1)
            "defaults.selection_background",
            "defaults.focus_ring_color",
            "defaults.selection_inactive_background",
            "defaults.text_selection_background",
            "defaults.text_selection_color",
            "defaults.font.color",
            "defaults.mono_font.color",
            // safety nets (Phase 2) — target fields
            "input.caret_color",
            "scrollbar.track_color",
            "spinner.fill_color",
            "popover.background_color",
            "list.background_color",
            "dialog.background_color",
            // widget-to-widget (Phase 4)
            "window.inactive_title_bar_background",
            "window.inactive_title_bar_text_color",
            "button.hover_text_color",
            "button.active_text_color",
            "tab.hover_text_color",
            "list.hover_text_color",
            "splitter.hover_color",
            "link.hover_text_color",
            "link.active_text_color",
            "list.alternate_row_background",
            // link.font.color override
            "link.font.color",
        ];

        for field in &no_inherit_fields {
            assert!(
                !all_inherited_targets.contains(&field.as_str()),
                "[no_inheritance] field '{field}' is listed as no-inherit but appears \
                 in an inheritance target list. Either remove the inheritance rule or \
                 remove the field from [no_inheritance]."
            );
        }
    }
}
