// Theme validation: orchestrate defaults extraction, per-widget dispatch, range checks,
// and ResolvedThemeVariant construction.
//
// Helper functions, range-check utilities, and ValidateNested trait live in validate_helpers.rs.

use super::validate_helpers::{self, require, require_font, require_text_scale_entry, DEFAULT_FONT_DPI};
use crate::error::ThemeResolutionError;
use crate::model::resolved::{
    ResolvedIconSizes, ResolvedTextScale, ResolvedThemeDefaults, ResolvedThemeVariant,
};
use crate::model::ThemeVariant;

impl ThemeVariant {
    // --- validate() ---

    /// Convert this ThemeVariant into a [`ResolvedThemeVariant`] with all fields guaranteed.
    ///
    /// Should be called after [`resolve()`](ThemeVariant::resolve). Walks every field
    /// and collects missing (None) field paths, then validates that numeric values
    /// are within legal ranges (e.g., spacing >= 0, opacity 0..=1, font weight
    /// 100..=900). Returns `Ok(ResolvedThemeVariant)` if all fields are populated
    /// and in range.
    ///
    /// # Errors
    ///
    /// Returns [`crate::Error::Resolution`] containing a [`ThemeResolutionError`]
    /// with all missing field paths and out-of-range diagnostics.
    // Per-widget extraction is generated by define_widget_pair! validate_widget().
    // Only defaults, text_scale, and range checks remain hand-written.
    #[must_use = "this returns the validation result; handle the Result or propagate with ?"]
    pub fn validate(&self) -> crate::Result<ResolvedThemeVariant> {
        let mut missing = Vec::new();

        // --- defaults ---

        // Extract DPI for FontSize::to_px conversion throughout validate().
        let dpi = self.defaults.font_dpi.unwrap_or(DEFAULT_FONT_DPI);

        let defaults_font = require_font(&self.defaults.font, "defaults.font", dpi, &mut missing);
        let defaults_line_height = require(
            &self.defaults.line_height,
            "defaults.line_height",
            &mut missing,
        );
        let defaults_mono_font = require_font(
            &self.defaults.mono_font,
            "defaults.mono_font",
            dpi,
            &mut missing,
        );

        let defaults_background = require(
            &self.defaults.background_color,
            "defaults.background_color",
            &mut missing,
        );
        let defaults_foreground = require(
            &self.defaults.text_color,
            "defaults.text_color",
            &mut missing,
        );
        let defaults_accent = require(
            &self.defaults.accent_color,
            "defaults.accent_color",
            &mut missing,
        );
        let defaults_accent_foreground = require(
            &self.defaults.accent_text_color,
            "defaults.accent_text_color",
            &mut missing,
        );
        let defaults_surface = require(
            &self.defaults.surface_color,
            "defaults.surface_color",
            &mut missing,
        );
        let defaults_border = require(
            &self.defaults.border.color,
            "defaults.border.color",
            &mut missing,
        );
        let defaults_muted = require(
            &self.defaults.muted_color,
            "defaults.muted_color",
            &mut missing,
        );
        let defaults_shadow = require(
            &self.defaults.shadow_color,
            "defaults.shadow_color",
            &mut missing,
        );
        let defaults_link = require(
            &self.defaults.link_color,
            "defaults.link_color",
            &mut missing,
        );
        let defaults_selection = require(
            &self.defaults.selection_background,
            "defaults.selection_background",
            &mut missing,
        );
        let defaults_selection_foreground = require(
            &self.defaults.selection_text_color,
            "defaults.selection_text_color",
            &mut missing,
        );
        let defaults_selection_inactive = require(
            &self.defaults.selection_inactive_background,
            "defaults.selection_inactive_background",
            &mut missing,
        );
        let defaults_disabled_foreground = require(
            &self.defaults.disabled_text_color,
            "defaults.disabled_text_color",
            &mut missing,
        );

        let defaults_danger = require(
            &self.defaults.danger_color,
            "defaults.danger_color",
            &mut missing,
        );
        let defaults_danger_foreground = require(
            &self.defaults.danger_text_color,
            "defaults.danger_text_color",
            &mut missing,
        );
        let defaults_warning = require(
            &self.defaults.warning_color,
            "defaults.warning_color",
            &mut missing,
        );
        let defaults_warning_foreground = require(
            &self.defaults.warning_text_color,
            "defaults.warning_text_color",
            &mut missing,
        );
        let defaults_success = require(
            &self.defaults.success_color,
            "defaults.success_color",
            &mut missing,
        );
        let defaults_success_foreground = require(
            &self.defaults.success_text_color,
            "defaults.success_text_color",
            &mut missing,
        );
        let defaults_info = require(
            &self.defaults.info_color,
            "defaults.info_color",
            &mut missing,
        );
        let defaults_info_foreground = require(
            &self.defaults.info_text_color,
            "defaults.info_text_color",
            &mut missing,
        );

        let defaults_radius = require(
            &self.defaults.border.corner_radius,
            "defaults.border.corner_radius",
            &mut missing,
        );
        let defaults_radius_lg = require(
            &self.defaults.border.corner_radius_lg,
            "defaults.border.corner_radius_lg",
            &mut missing,
        );
        let defaults_frame_width = require(
            &self.defaults.border.line_width,
            "defaults.border.line_width",
            &mut missing,
        );
        let defaults_disabled_opacity = require(
            &self.defaults.disabled_opacity,
            "defaults.disabled_opacity",
            &mut missing,
        );
        let defaults_border_opacity = require(
            &self.defaults.border.opacity,
            "defaults.border.opacity",
            &mut missing,
        );
        let defaults_shadow_enabled = require(
            &self.defaults.border.shadow_enabled,
            "defaults.border.shadow_enabled",
            &mut missing,
        );

        let defaults_focus_ring_color = require(
            &self.defaults.focus_ring_color,
            "defaults.focus_ring_color",
            &mut missing,
        );
        let defaults_focus_ring_width = require(
            &self.defaults.focus_ring_width,
            "defaults.focus_ring_width",
            &mut missing,
        );
        let defaults_focus_ring_offset = require(
            &self.defaults.focus_ring_offset,
            "defaults.focus_ring_offset",
            &mut missing,
        );

        let defaults_border_padding_h = require(
            &self.defaults.border.padding_horizontal,
            "defaults.border.padding_horizontal",
            &mut missing,
        );
        let defaults_border_padding_v = require(
            &self.defaults.border.padding_vertical,
            "defaults.border.padding_vertical",
            &mut missing,
        );
        let defaults_text_selection_background = require(
            &self.defaults.text_selection_background,
            "defaults.text_selection_background",
            &mut missing,
        );
        let defaults_text_selection_color = require(
            &self.defaults.text_selection_color,
            "defaults.text_selection_color",
            &mut missing,
        );

        let defaults_icon_sizes_toolbar = require(
            &self.defaults.icon_sizes.toolbar,
            "defaults.icon_sizes.toolbar",
            &mut missing,
        );
        let defaults_icon_sizes_small = require(
            &self.defaults.icon_sizes.small,
            "defaults.icon_sizes.small",
            &mut missing,
        );
        let defaults_icon_sizes_large = require(
            &self.defaults.icon_sizes.large,
            "defaults.icon_sizes.large",
            &mut missing,
        );
        let defaults_icon_sizes_dialog = require(
            &self.defaults.icon_sizes.dialog,
            "defaults.icon_sizes.dialog",
            &mut missing,
        );
        let defaults_icon_sizes_panel = require(
            &self.defaults.icon_sizes.panel,
            "defaults.icon_sizes.panel",
            &mut missing,
        );

        // font_dpi records the DPI used for pt-to-px conversion (or the default).
        let defaults_font_dpi = dpi;

        let defaults_text_scaling_factor = require(
            &self.defaults.text_scaling_factor,
            "defaults.text_scaling_factor",
            &mut missing,
        );
        let defaults_reduce_motion = require(
            &self.defaults.reduce_motion,
            "defaults.reduce_motion",
            &mut missing,
        );
        let defaults_high_contrast = require(
            &self.defaults.high_contrast,
            "defaults.high_contrast",
            &mut missing,
        );
        let defaults_reduce_transparency = require(
            &self.defaults.reduce_transparency,
            "defaults.reduce_transparency",
            &mut missing,
        );

        // --- text_scale ---

        let ts_caption = require_text_scale_entry(
            &self.text_scale.caption,
            "text_scale.caption",
            dpi,
            &mut missing,
        );
        let ts_section_heading = require_text_scale_entry(
            &self.text_scale.section_heading,
            "text_scale.section_heading",
            dpi,
            &mut missing,
        );
        let ts_dialog_title = require_text_scale_entry(
            &self.text_scale.dialog_title,
            "text_scale.dialog_title",
            dpi,
            &mut missing,
        );
        let ts_display = require_text_scale_entry(
            &self.text_scale.display,
            "text_scale.display",
            dpi,
            &mut missing,
        );

        // --- construct defaults and text_scale structs ---
        //
        // Built here (before range checks) so check_defaults_ranges() can
        // operate on the struct references, and the final construction can
        // reuse them directly.

        use crate::model::border::ResolvedBorderSpec;

        let defaults = ResolvedThemeDefaults {
            font: defaults_font,
            line_height: defaults_line_height,
            mono_font: defaults_mono_font,
            background_color: defaults_background,
            text_color: defaults_foreground,
            accent_color: defaults_accent,
            accent_text_color: defaults_accent_foreground,
            surface_color: defaults_surface,
            border: ResolvedBorderSpec {
                color: defaults_border,
                corner_radius: defaults_radius,
                corner_radius_lg: defaults_radius_lg,
                line_width: defaults_frame_width,
                opacity: defaults_border_opacity,
                shadow_enabled: defaults_shadow_enabled,
                padding_horizontal: defaults_border_padding_h,
                padding_vertical: defaults_border_padding_v,
            },
            muted_color: defaults_muted,
            shadow_color: defaults_shadow,
            link_color: defaults_link,
            selection_background: defaults_selection,
            selection_text_color: defaults_selection_foreground,
            selection_inactive_background: defaults_selection_inactive,
            text_selection_background: defaults_text_selection_background,
            text_selection_color: defaults_text_selection_color,
            disabled_text_color: defaults_disabled_foreground,
            danger_color: defaults_danger,
            danger_text_color: defaults_danger_foreground,
            warning_color: defaults_warning,
            warning_text_color: defaults_warning_foreground,
            success_color: defaults_success,
            success_text_color: defaults_success_foreground,
            info_color: defaults_info,
            info_text_color: defaults_info_foreground,
            disabled_opacity: defaults_disabled_opacity,
            focus_ring_color: defaults_focus_ring_color,
            focus_ring_width: defaults_focus_ring_width,
            focus_ring_offset: defaults_focus_ring_offset,
            icon_sizes: ResolvedIconSizes {
                toolbar: defaults_icon_sizes_toolbar,
                small: defaults_icon_sizes_small,
                large: defaults_icon_sizes_large,
                dialog: defaults_icon_sizes_dialog,
                panel: defaults_icon_sizes_panel,
            },
            font_dpi: defaults_font_dpi,
            text_scaling_factor: defaults_text_scaling_factor,
            reduce_motion: defaults_reduce_motion,
            high_contrast: defaults_high_contrast,
            reduce_transparency: defaults_reduce_transparency,
        };
        let text_scale = ResolvedTextScale {
            caption: ts_caption,
            section_heading: ts_section_heading,
            dialog_title: ts_dialog_title,
            display: ts_display,
        };

        // --- defaults and text_scale range checks ---
        validate_helpers::check_defaults_ranges(&defaults, &text_scale, &mut missing);

        // --- per-widget extraction (generated by define_widget_pair!) ---

        use crate::model::widgets::*;

        let window =
            ResolvedWindowTheme::validate_widget(&self.window, "window", dpi, &mut missing);
        let button =
            ResolvedButtonTheme::validate_widget(&self.button, "button", dpi, &mut missing);
        let input = ResolvedInputTheme::validate_widget(&self.input, "input", dpi, &mut missing);
        let checkbox =
            ResolvedCheckboxTheme::validate_widget(&self.checkbox, "checkbox", dpi, &mut missing);
        let menu = ResolvedMenuTheme::validate_widget(&self.menu, "menu", dpi, &mut missing);
        let tooltip =
            ResolvedTooltipTheme::validate_widget(&self.tooltip, "tooltip", dpi, &mut missing);
        let scrollbar = ResolvedScrollbarTheme::validate_widget(
            &self.scrollbar,
            "scrollbar",
            dpi,
            &mut missing,
        );
        let slider =
            ResolvedSliderTheme::validate_widget(&self.slider, "slider", dpi, &mut missing);
        let progress_bar = ResolvedProgressBarTheme::validate_widget(
            &self.progress_bar,
            "progress_bar",
            dpi,
            &mut missing,
        );
        let tab = ResolvedTabTheme::validate_widget(&self.tab, "tab", dpi, &mut missing);
        let sidebar =
            ResolvedSidebarTheme::validate_widget(&self.sidebar, "sidebar", dpi, &mut missing);
        let toolbar =
            ResolvedToolbarTheme::validate_widget(&self.toolbar, "toolbar", dpi, &mut missing);
        let status_bar = ResolvedStatusBarTheme::validate_widget(
            &self.status_bar,
            "status_bar",
            dpi,
            &mut missing,
        );
        let list = ResolvedListTheme::validate_widget(&self.list, "list", dpi, &mut missing);
        let popover =
            ResolvedPopoverTheme::validate_widget(&self.popover, "popover", dpi, &mut missing);
        let splitter =
            ResolvedSplitterTheme::validate_widget(&self.splitter, "splitter", dpi, &mut missing);
        let separator = ResolvedSeparatorTheme::validate_widget(
            &self.separator,
            "separator",
            dpi,
            &mut missing,
        );
        let switch =
            ResolvedSwitchTheme::validate_widget(&self.switch, "switch", dpi, &mut missing);
        let dialog =
            ResolvedDialogTheme::validate_widget(&self.dialog, "dialog", dpi, &mut missing);
        let spinner =
            ResolvedSpinnerTheme::validate_widget(&self.spinner, "spinner", dpi, &mut missing);
        let combo_box =
            ResolvedComboBoxTheme::validate_widget(&self.combo_box, "combo_box", dpi, &mut missing);
        let segmented_control = ResolvedSegmentedControlTheme::validate_widget(
            &self.segmented_control,
            "segmented_control",
            dpi,
            &mut missing,
        );
        let card = ResolvedCardTheme::validate_widget(&self.card, "card", dpi, &mut missing);
        let expander =
            ResolvedExpanderTheme::validate_widget(&self.expander, "expander", dpi, &mut missing);
        let link = ResolvedLinkTheme::validate_widget(&self.link, "link", dpi, &mut missing);

        let icon_set = require(&self.icon_set, "icon_set", &mut missing);
        let icon_theme = require(&self.icon_theme, "icon_theme", &mut missing);

        // --- per-widget range checks ---
        // (These will move to check_ranges() methods on each Resolved* struct in Task 2.)

        use validate_helpers::{
            check_min_max, check_non_negative, check_positive, check_range_f32, check_range_u16,
        };

        // window font: size > 0, weight 100..=900
        check_positive(
            window.title_bar_font.size,
            "window.title_bar_font.size",
            &mut missing,
        );
        check_range_u16(
            window.title_bar_font.weight,
            100,
            900,
            "window.title_bar_font.weight",
            &mut missing,
        );

        // button: geometry >= 0, opacity 0..=1, font size > 0, font weight 100..=900
        check_non_negative(button.min_width, "button.min_width", &mut missing);
        check_non_negative(button.min_height, "button.min_height", &mut missing);
        check_non_negative(button.icon_text_gap, "button.icon_text_gap", &mut missing);
        check_range_f32(
            button.disabled_opacity,
            0.0,
            1.0,
            "button.disabled_opacity",
            &mut missing,
        );
        check_positive(button.font.size, "button.font.size", &mut missing);
        check_range_u16(
            button.font.weight,
            100,
            900,
            "button.font.weight",
            &mut missing,
        );

        // input: geometry >= 0, opacity 0..=1, font size > 0, font weight 100..=900
        check_non_negative(input.min_height, "input.min_height", &mut missing);
        check_range_f32(
            input.disabled_opacity,
            0.0,
            1.0,
            "input.disabled_opacity",
            &mut missing,
        );
        check_positive(input.font.size, "input.font.size", &mut missing);
        check_range_u16(
            input.font.weight,
            100,
            900,
            "input.font.weight",
            &mut missing,
        );

        // checkbox: geometry >= 0, opacity 0..=1, font size > 0, font weight 100..=900
        check_non_negative(
            checkbox.indicator_width,
            "checkbox.indicator_width",
            &mut missing,
        );
        check_non_negative(checkbox.label_gap, "checkbox.label_gap", &mut missing);
        check_range_f32(
            checkbox.disabled_opacity,
            0.0,
            1.0,
            "checkbox.disabled_opacity",
            &mut missing,
        );
        check_positive(checkbox.font.size, "checkbox.font.size", &mut missing);
        check_range_u16(
            checkbox.font.weight,
            100,
            900,
            "checkbox.font.weight",
            &mut missing,
        );

        // menu: geometry >= 0, font size > 0, font weight 100..=900
        check_non_negative(menu.row_height, "menu.row_height", &mut missing);
        check_non_negative(menu.icon_text_gap, "menu.icon_text_gap", &mut missing);
        check_non_negative(menu.icon_size, "menu.icon_size", &mut missing);
        check_positive(menu.font.size, "menu.font.size", &mut missing);
        check_range_u16(menu.font.weight, 100, 900, "menu.font.weight", &mut missing);

        // tooltip: geometry >= 0, font size > 0, font weight 100..=900
        check_non_negative(tooltip.max_width, "tooltip.max_width", &mut missing);
        check_positive(tooltip.font.size, "tooltip.font.size", &mut missing);
        check_range_u16(
            tooltip.font.weight,
            100,
            900,
            "tooltip.font.weight",
            &mut missing,
        );

        // scrollbar: geometry >= 0
        check_non_negative(
            scrollbar.groove_width,
            "scrollbar.groove_width",
            &mut missing,
        );
        check_non_negative(
            scrollbar.min_thumb_length,
            "scrollbar.min_thumb_length",
            &mut missing,
        );
        check_non_negative(scrollbar.thumb_width, "scrollbar.thumb_width", &mut missing);

        // slider: geometry >= 0, opacity 0..=1
        check_non_negative(slider.track_height, "slider.track_height", &mut missing);
        check_non_negative(slider.thumb_diameter, "slider.thumb_diameter", &mut missing);
        check_non_negative(
            slider.tick_mark_length,
            "slider.tick_mark_length",
            &mut missing,
        );
        check_range_f32(
            slider.disabled_opacity,
            0.0,
            1.0,
            "slider.disabled_opacity",
            &mut missing,
        );

        // progress_bar: geometry >= 0
        check_non_negative(
            progress_bar.track_height,
            "progress_bar.track_height",
            &mut missing,
        );
        check_non_negative(
            progress_bar.min_width,
            "progress_bar.min_width",
            &mut missing,
        );

        // tab: geometry >= 0, font size > 0, font weight 100..=900
        check_non_negative(tab.min_width, "tab.min_width", &mut missing);
        check_non_negative(tab.min_height, "tab.min_height", &mut missing);
        check_positive(tab.font.size, "tab.font.size", &mut missing);
        check_range_u16(tab.font.weight, 100, 900, "tab.font.weight", &mut missing);

        // sidebar: font size > 0, font weight 100..=900
        check_positive(sidebar.font.size, "sidebar.font.size", &mut missing);
        check_range_u16(
            sidebar.font.weight,
            100,
            900,
            "sidebar.font.weight",
            &mut missing,
        );

        // toolbar: geometry >= 0, font size > 0, font weight 100..=900
        check_non_negative(toolbar.bar_height, "toolbar.bar_height", &mut missing);
        check_non_negative(toolbar.item_gap, "toolbar.item_gap", &mut missing);
        check_non_negative(toolbar.icon_size, "toolbar.icon_size", &mut missing);
        check_positive(toolbar.font.size, "toolbar.font.size", &mut missing);
        check_range_u16(
            toolbar.font.weight,
            100,
            900,
            "toolbar.font.weight",
            &mut missing,
        );

        // status_bar: font size > 0, font weight 100..=900
        check_positive(status_bar.font.size, "status_bar.font.size", &mut missing);
        check_range_u16(
            status_bar.font.weight,
            100,
            900,
            "status_bar.font.weight",
            &mut missing,
        );

        // list: geometry >= 0, font size > 0, font weight 100..=900
        check_non_negative(list.row_height, "list.row_height", &mut missing);
        check_positive(list.item_font.size, "list.item_font.size", &mut missing);
        check_range_u16(
            list.item_font.weight,
            100,
            900,
            "list.item_font.weight",
            &mut missing,
        );
        check_positive(list.header_font.size, "list.header_font.size", &mut missing);
        check_range_u16(
            list.header_font.weight,
            100,
            900,
            "list.header_font.weight",
            &mut missing,
        );

        // popover: font size > 0, font weight 100..=900
        check_positive(popover.font.size, "popover.font.size", &mut missing);
        check_range_u16(
            popover.font.weight,
            100,
            900,
            "popover.font.weight",
            &mut missing,
        );

        // splitter: width >= 0
        check_non_negative(
            splitter.divider_width,
            "splitter.divider_width",
            &mut missing,
        );

        // separator: line_width >= 0
        check_non_negative(separator.line_width, "separator.line_width", &mut missing);

        // switch: geometry >= 0, opacity 0..=1
        check_non_negative(switch.track_width, "switch.track_width", &mut missing);
        check_non_negative(switch.track_height, "switch.track_height", &mut missing);
        check_non_negative(switch.thumb_diameter, "switch.thumb_diameter", &mut missing);
        check_non_negative(switch.track_radius, "switch.track_radius", &mut missing);
        check_range_f32(
            switch.disabled_opacity,
            0.0,
            1.0,
            "switch.disabled_opacity",
            &mut missing,
        );

        // dialog: geometry >= 0, font size > 0, font weight 100..=900
        check_non_negative(dialog.min_width, "dialog.min_width", &mut missing);
        check_non_negative(dialog.max_width, "dialog.max_width", &mut missing);
        check_non_negative(dialog.min_height, "dialog.min_height", &mut missing);
        check_non_negative(dialog.max_height, "dialog.max_height", &mut missing);
        check_non_negative(dialog.button_gap, "dialog.button_gap", &mut missing);
        check_non_negative(dialog.icon_size, "dialog.icon_size", &mut missing);
        check_positive(
            dialog.title_font.size,
            "dialog.title_font.size",
            &mut missing,
        );
        check_range_u16(
            dialog.title_font.weight,
            100,
            900,
            "dialog.title_font.weight",
            &mut missing,
        );

        // dialog: body_font size > 0, weight 100..=900
        check_positive(dialog.body_font.size, "dialog.body_font.size", &mut missing);
        check_range_u16(
            dialog.body_font.weight,
            100,
            900,
            "dialog.body_font.weight",
            &mut missing,
        );

        // dialog: cross-field min/max constraints
        check_min_max(
            dialog.min_width,
            dialog.max_width,
            "dialog.min_width",
            "dialog.max_width",
            &mut missing,
        );
        check_min_max(
            dialog.min_height,
            dialog.max_height,
            "dialog.min_height",
            "dialog.max_height",
            &mut missing,
        );

        // spinner: geometry >= 0
        check_non_negative(spinner.diameter, "spinner.diameter", &mut missing);
        check_non_negative(spinner.min_diameter, "spinner.min_diameter", &mut missing);
        check_non_negative(spinner.stroke_width, "spinner.stroke_width", &mut missing);

        // link: font size > 0, font weight 100..=900
        check_positive(link.font.size, "link.font.size", &mut missing);
        check_range_u16(link.font.weight, 100, 900, "link.font.weight", &mut missing);

        // combo_box: geometry >= 0, opacity 0..=1, font size > 0, font weight 100..=900
        check_non_negative(combo_box.min_height, "combo_box.min_height", &mut missing);
        check_non_negative(combo_box.min_width, "combo_box.min_width", &mut missing);
        check_non_negative(
            combo_box.arrow_icon_size,
            "combo_box.arrow_icon_size",
            &mut missing,
        );
        check_non_negative(
            combo_box.arrow_area_width,
            "combo_box.arrow_area_width",
            &mut missing,
        );
        check_range_f32(
            combo_box.disabled_opacity,
            0.0,
            1.0,
            "combo_box.disabled_opacity",
            &mut missing,
        );
        check_positive(combo_box.font.size, "combo_box.font.size", &mut missing);
        check_range_u16(
            combo_box.font.weight,
            100,
            900,
            "combo_box.font.weight",
            &mut missing,
        );

        // segmented_control: geometry >= 0, opacity 0..=1, font size > 0, font weight 100..=900
        check_non_negative(
            segmented_control.segment_height,
            "segmented_control.segment_height",
            &mut missing,
        );
        check_non_negative(
            segmented_control.separator_width,
            "segmented_control.separator_width",
            &mut missing,
        );
        check_range_f32(
            segmented_control.disabled_opacity,
            0.0,
            1.0,
            "segmented_control.disabled_opacity",
            &mut missing,
        );
        check_positive(
            segmented_control.font.size,
            "segmented_control.font.size",
            &mut missing,
        );
        check_range_u16(
            segmented_control.font.weight,
            100,
            900,
            "segmented_control.font.weight",
            &mut missing,
        );

        // expander: geometry >= 0, font size > 0, font weight 100..=900
        check_non_negative(
            expander.header_height,
            "expander.header_height",
            &mut missing,
        );
        check_non_negative(
            expander.arrow_icon_size,
            "expander.arrow_icon_size",
            &mut missing,
        );
        check_positive(expander.font.size, "expander.font.size", &mut missing);
        check_range_u16(
            expander.font.weight,
            100,
            900,
            "expander.font.weight",
            &mut missing,
        );

        // --- check for missing fields and range errors ---

        if !missing.is_empty() {
            return Err(crate::Error::Resolution(ThemeResolutionError {
                missing_fields: missing,
            }));
        }

        // All fields present -- construct ResolvedThemeVariant.

        Ok(ResolvedThemeVariant {
            defaults,
            text_scale,
            window,
            button,
            input,
            checkbox,
            menu,
            tooltip,
            scrollbar,
            slider,
            progress_bar,
            tab,
            sidebar,
            toolbar,
            status_bar,
            list,
            popover,
            splitter,
            separator,
            switch,
            dialog,
            spinner,
            combo_box,
            segmented_control,
            card,
            expander,
            link,
            icon_set,
            icon_theme,
        })
    }
}
